# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Cypress-Mochawesome Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  cypress-run:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        containers: [1, 2, 3, 4, 5, 6]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    # Install NPM dependencies, cache them correctly
    # and run all Cypress tests
    - name: Cypress run
      uses: cypress-io/github-action@v4.2.1
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        browser: chrome
        headed: true
    - run: npm ci
    - run: npm run build --if-present
